name: Run CI Checks

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install uv
        run: pip install uv

      - name: Install dependencies
        run: uv sync

      - name: Check formatting with Ruff
        working-directory: packages/datacommons-mcp
        run: uv run ruff format --check

      - name: Lint with Ruff
        working-directory: packages/datacommons-mcp
        run: uv run ruff check

  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for changed test paths
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            run_tests:
              - 'packages/datacommons-mcp/datacommons_mcp/**'
              - 'packages/datacommons-mcp/tests/**'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        run: pip install uv

      - name: Install dependencies
        run: uv sync

      - name: Run tests with pytest. Skip eval tests.
        if: steps.filter.outputs.run_tests == 'true'
        run: uv run --extra test pytest -k "not eval"

 
  build-and-test-wheel:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        run: pip install uv

      - name: Build wheel
        working-directory: packages/datacommons-mcp
        run: uv build
 
      - name: Test running server from installed wheel
        env:
          DC_API_KEY: test
        run: |
          # Create and activate a temporary environment
          uv venv wheel_test_venv
          source wheel_test_venv/bin/activate

          # Find the built wheel file and install it
          # Use an absolute path to avoid ambiguity
          WHEEL_FILE=$(find ${{ github.workspace }}/dist -name "*.whl")
          echo "Installing wheel: $WHEEL_FILE"
          uv pip install --quiet "$WHEEL_FILE"

          # Start the server in the background
          echo "Starting server in background, logging to server.log..."
          # Redirect stdout and stderr to a log file
          datacommons-mcp serve http --port 8088 &> server.log &
          SERVER_PID=$!

          # Poll the server to see if it's healthy, with a 15-second timeout
          echo "Waiting for server to become healthy..."
          for i in {1..15}; do
            if curl -s --fail http://localhost:8088/health > /dev/null; then
              echo "Server started successfully!"
              kill $SERVER_PID
              exit 0
            fi
            sleep 1
          done

          echo "Error: Server did not start in time."
          echo "--- Server Logs (server.log) ---"
          cat server.log
          echo "--------------------------------"
          kill $SERVER_PID
          exit 1

  ci-checks:
    # This job aggregates the status of all parallel CI jobs.
    # It's used as the single required status check in branch protection rules.
    runs-on: ubuntu-latest
    needs:
      - lint-and-format
      - unit-tests
      - build-and-test-wheel
    # The 'if: always()' ensures this job runs even if dependencies fail,
    # correctly reporting a "failure" status for the PR.
    if: always()
    steps:
      - name: Report overall CI status
        run: |
          if [[ "${{ needs.lint-and-format.result }}" == "success" && \
                "${{ needs.unit-tests.result }}" == "success" && \
                "${{ needs.build-and-test-wheel.result }}" == "success" ]]; then
            echo "All CI checks passed!"
            exit 0
          else
            echo "One or more CI checks failed."
            exit 1
          fi