name: Run CI Checks

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  ci-checks:
    runs-on: ubuntu-latest

    # Run tests on python 3.11 and 3.12
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for changed test paths
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            run_tests:
              - 'packages/datacommons-mcp/datacommons_mcp/**'
              - 'packages/datacommons-mcp/tests/**'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        run: pip install uv

      - name: Install dependencies
        # This will install all dependencies from the workspace pyproject.toml
        run: uv sync

      - name: Check formatting with Ruff
        # Run from the package directory
        working-directory: packages/datacommons-mcp
        # The --check flag will fail if the code is not formatted correctly
        run: uv run ruff format --check

      - name: Lint with Ruff
        working-directory: packages/datacommons-mcp
        run: uv run ruff check

      - name: Run tests with pytest. Skip eval tests.
        # Run unit tests if code in the datacommons-mcp package or tests directory changed
        if: steps.filter.outputs.run_tests == 'true'
        run: uv run --extra test pytest -k "not eval"

      - name: Build wheel
        # Build from the package directory
        working-directory: packages/datacommons-mcp
        run: uv build
 
      - name: Test running server from installed wheel
        env:
          DC_API_KEY: test
        run: |
          # Create and activate a temporary environment
          uv venv wheel_test_venv
          source wheel_test_venv/bin/activate

          # Find the built wheel file and install it
          # Use an absolute path to avoid ambiguity
          WHEEL_FILE=$(find ${{ github.workspace }}/dist -name "*.whl")
          echo "Installing wheel: $WHEEL_FILE"
          uv pip install "$WHEEL_FILE"

          # Start the server in the background
          echo "Starting server in background, logging to server.log..."
          # Redirect stdout and stderr to a log file
          datacommons-mcp serve http --port 8088 &> server.log &
          SERVER_PID=$!

          # Poll the server to see if it's healthy, with a 15-second timeout
          echo "Waiting for server to become healthy..."
          for i in {1..15}; do
            if curl -s --fail http://localhost:8088/health > /dev/null; then
              echo "Server started successfully!"
              kill $SERVER_PID
              exit 0
            fi
            sleep 1
          done

          echo "Error: Server did not start in time."
          echo "--- Server Logs (server.log) ---"
          cat server.log
          echo "--------------------------------"
          kill $SERVER_PID
          exit 1
